// Generated by CoffeeScript 1.9.0
(function() {
  var api_actions, boot_compute_service, boot_console_service, broker_context, read_options;

  boot_compute_service = function() {
    var context;
    console.log("Booting Compute Service");
    return context = broker_context();
  };

  api_actions = {};

  api_actions.load_client = function(req, res) {
    return res.send('Hello World!');
  };

  boot_console_service = function() {
    var app, express, server;
    console.log("Booting Console Service");
    express = require("express");
    app = express();
    app.get('/', api_actions.load_client);
    return server = app.listen(3000, function() {
      var host, port;
      host = server.address().address;
      port = server.address().port;
      return console.log('Console service listening at http://%s:%s', host, port);
    });
  };

  broker_context = function() {
    return require('rabbit.js').createContext('amqp://localhost');
  };

  read_options = function() {
    var args, argv, mode;
    argv = require("argv");
    argv.info(' Punk. Invoke with console or compute ');
    argv.version("0.0.0");
    argv.option({
      name: "broker",
      short: "b",
      type: "string"
    });
    argv.option({
      name: "port",
      short: "p",
      type: "int"
    });
    args = argv.run();
    console.log(args["targets"][0]);
    mode = args["targets"][0];
    if (mode === "compute") {
      return boot_compute_service();
    } else if (mode === "console") {
      return boot_console_service();
    } else {
      return console.log("You gotta tell me compute or console");
    }
  };

  read_options();

}).call(this);
