// Generated by CoffeeScript 1.9.0
(function() {
  var boot_compute_service, boot_console_service, broker_context, punk_log, read_options;

  punk_log = function(msg) {
    var date;
    date = new Date();
    return console.log("[punk] " + date + " " + msg);
  };

  boot_compute_service = function() {
    var context;
    console.log("Booting Compute Service");
    return context = broker_context();
  };

  boot_console_service = function() {
    var context, express;
    console.log("Booting Console Service");
    express = require("express");
    return context = broker_context();
  };

  broker_context = function() {
    return require('rabbit.js').createContext('amqp://localhost');
  };

  read_options = function() {
    var args, argv, mode;
    argv = require("argv");
    argv.info(' Punk. Invoke with console or compute ');
    argv.version("0.0.0");
    argv.option({
      name: "broker",
      short: "b",
      type: "string"
    });
    args = argv.run();
    console.log(args["targets"][0]);
    mode = args["targets"][0];
    if (mode === "compute") {
      return boot_compute_service();
    } else if (mode === "console") {
      return boot_console_service();
    } else {
      return console.log("You gotta tell me compute or console");
    }
  };

  read_options();

}).call(this);
