// Generated by CoffeeScript 1.9.0
(function() {
  var express;

  express = require("express");

  module.exports = {
    init: function(punkfile) {
      return console.log("Got my punkfile right here: " + punkfile);
    },
    send: function(message, to_punk) {
      return console.log("Sending message [" + message + "] to punk [" + to_punk + "]");
    },
    read_message: function(from_punk) {
      console.log("Reading message from [" + from_punk + "]");
      return {
        hello: "punk"
      };
    }
  };

}).call(this);
